import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  renderToBuffer,
} from '@react-pdf/renderer';
import { getRating, type AuditScores } from './scoring';

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica' },
  heading: { fontSize: 20, marginBottom: 4 },
  subheading: { fontSize: 11, color: '#666666', marginBottom: 24 },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottom: '1px solid #eeeeee',
  },
  label: {
    fontSize: 12,
  },
  score: { fontSize: 12, fontFamily: 'Helvetica-Bold' },
  footer: { fontSize: 9, color: '#999999', marginTop: 32 },
});

interface ReportDocumentProps {
  url: string;
  scores: AuditScores;
}

function ReportDocument({ url, scores }: ReportDocumentProps) {
  const rows: [string, number][] = [
    ['Performance', scores.performance],
    ['SEO', scores.seo],
    ['Accessibility', scores.accessibility],
    ['Best Practices', scores.bestPractices],
  ];

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.heading}>
          Hotis Studio - Website Health Check Report
        </Text>
        <Text style={styles.subheading}>{url}</Text>

        {rows.map(([label, score]) => (
          <View key={label} style={styles.row}>
            <Text style={styles.label}>{label}</Text>
            <Text style={styles.score}>
              {score}/100 - {getRating(score).replace('-', ' ')}
            </Text>
          </View>
        ))}

        <Text style={styles.footer}>
          Generated by Hotis Studio - Website Health Check
        </Text>
      </Page>
    </Document>
  );
}

export async function generateReportPdf(
  url: string,
  scores: AuditScores
): Promise<Buffer> {
  return renderToBuffer(<ReportDocument url={url} scores={scores} />);
}
